# Application Configuration for Spring Boot Restaurant Service

# Server configuration
server:
  port: 8080 # The port on which the application will run.

# Spring application configuration
spring:
  application:
    name: restaurant # Sets the name of the Spring application to 'restaurant'.

  # DataSource configuration for H2 in-memory database
  datasource:
    url: jdbc:h2:mem:restaurantDb # JDBC URL for H2 in-memory database named 'restaurantDb'.
    driver-class-name: org.h2.Driver # Driver class for H2 database.
    username: 'sa' # Username for database connection (default for H2).
    password: '' # No password set for the H2 in-memory database.

  # H2 console configuration
  h2:
    console:
      enabled: true # Enables the H2 web console for easy access to the in-memory database.

  # JPA (Java Persistence API) configuration
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect # Specifies the SQL dialect to be used by Hibernate for the H2 database.
        format_sql: 'true' # Ensures the SQL queries generated by Hibernate are formatted and easier to read.
    hibernate:
      ddl-auto: validate # Hibernate will validate the schema but not modify the database structure.
    show-sql: 'true' # Enables logging of all SQL statements generated by Hibernate.

  # Flyway migration configuration
  flyway:
    enabled: true # Enables Flyway for managing database migrations.
    baseline-on-migrate: true # Ensures that Flyway uses the baseline version on migration to handle existing databases.
    locations: classpath:db.migration # The directory where Flyway will look for migration scripts.

# Management endpoint configuration
management:
  endpoints:
    web:
      exposure:
        include: "*" # Exposes all available actuator endpoints via web for monitoring (health, info, etc.).
  endpoint:
    health:
      show-details: always # Ensures detailed health information is always shown when accessing the health endpoint.

# Eureka Client configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka # The URL of the Eureka server where this application will register.
    fetch-registry: true # Enables fetching of the Eureka registry to get the services registered with Eureka.
    register-with-eureka: true # Registers this service (restaurant) with the Eureka server for discovery by other services.