INSERT INTO restaurant (id, name, address, number_table, number_table_reserved) VALUES
   (NEXT VALUE FOR restaurant_id_sequence, 'Golden Spoon', '123 Main St', 15, 2),
   (NEXT VALUE FOR restaurant_id_sequence, 'Blue Ocean', '456 Pine Ave', 20, 4),
   (NEXT VALUE FOR restaurant_id_sequence, 'The Hungry Chef', '789 Elm Rd', 10, 1),
   (NEXT VALUE FOR restaurant_id_sequence, 'Spice Route', '101 Maple St', 25, 6),
   (NEXT VALUE FOR restaurant_id_sequence, 'La Bella', '202 Cedar Ln', 30, 8),
   (NEXT VALUE FOR restaurant_id_sequence, 'Urban Grill', '303 Oak Blvd', 18, 5),
   (NEXT VALUE FOR restaurant_id_sequence, 'Fusion Fiesta', '404 Spruce St', 12, 2),
   (NEXT VALUE FOR restaurant_id_sequence, 'Zen Garden', '505 Birch Way', 22, 7),
   (NEXT VALUE FOR restaurant_id_sequence, 'Café Delight', '606 Willow St', 16, 3),
   (NEXT VALUE FOR restaurant_id_sequence, 'Mountain View', '707 Poplar Rd', 14, 1),
   (NEXT VALUE FOR restaurant_id_sequence, 'Sunset Bistro', '808 Redwood Dr', 26, 9),
   (NEXT VALUE FOR restaurant_id_sequence, 'Riverfront Eatery', '909 Cypress Ave', 24, 6),
   (NEXT VALUE FOR restaurant_id_sequence, 'Garden of Flavors', '1010 Pinecrest Dr', 17, 2),
   (NEXT VALUE FOR restaurant_id_sequence, 'The Roaring Fork', '1111 Aspen Ln', 20, 5),
   (NEXT VALUE FOR restaurant_id_sequence, 'Taste of Tuscany', '1212 Juniper St', 27, 10),
   (NEXT VALUE FOR restaurant_id_sequence, 'Bistro on the Bay', '1313 Seaview Dr', 23, 8),
   (NEXT VALUE FOR restaurant_id_sequence, 'Culinary Haven', '1414 Meadow Ln', 19, 4),
   (NEXT VALUE FOR restaurant_id_sequence, 'Savory Street', '1515 Highland Dr', 21, 7),
   (NEXT VALUE FOR restaurant_id_sequence, 'Fire & Ice Grill', '1616 River Rd', 28, 9),
   (NEXT VALUE FOR restaurant_id_sequence, 'The Rustic Fork', '1717 Hillside Ave', 22, 6),
   (NEXT VALUE FOR restaurant_id_sequence, 'Crimson Table', '1818 Forest Dr', 13, 1),
   (NEXT VALUE FOR restaurant_id_sequence, 'Euphoria Diner', '1919 Garden Ln', 18, 5),
   (NEXT VALUE FOR restaurant_id_sequence, 'Pasta House', '2020 Vineyard Dr', 25, 10),
   (NEXT VALUE FOR restaurant_id_sequence, 'The Secret Spice', '2121 Lakeshore Dr', 16, 3),
   (NEXT VALUE FOR restaurant_id_sequence, 'Vintage Vines', '2222 Summit Dr', 19, 4),
   (NEXT VALUE FOR restaurant_id_sequence, 'Coastal Cravings', '2323 Beachside Ln', 20, 5),
   (NEXT VALUE FOR restaurant_id_sequence, 'Gourmet Grill', '2424 Riverside Dr', 29, 8),
   (NEXT VALUE FOR restaurant_id_sequence, 'The Sizzling Plate', '2525 Ridgewood St', 12, 2),
   (NEXT VALUE FOR restaurant_id_sequence, 'Flavors of Asia', '2626 Bayview Ave', 21, 6),
   (NEXT VALUE FOR restaurant_id_sequence, 'Olive & Thyme', '2727 Hillsborough Rd', 17, 3);